version: "3.9"

services:
  wavely:
    image: sven42xyz/wavely:latest # Current digest: sha256:8820c3b51c636b225113860030e7652b27a32b3345f51c3681cef5a5ad1484ba
    container_name: wavely
    restart: unless-stopped

    # Expose the wavely port
    ports:
      - "4224:4224"

    # External directories
    volumes:
      - ./config:/app/config     # Place your wavely.cfg.yaml here
      - ./cache:/app/cache       # This directory is used to persist app and auth data
      - ./logs:/app/logs         # Logs will be outputted here

    # Wavely provides a health check interface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4224/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
